### ISSUE TITLE
Bug about REACHING_DEF

### ISSUE THREAD

**Issue by clccc** [ShiftLeftSecurity/joern#333]
I test the newest joern v1.0.186. I found that some reaching-def edges did not labeld VARIABLE.  A reaching-def edge should have an associate def-variable, is it right?
![image](https://user-images.githubusercontent.com/12693134/91782721-83ad9d00-ec30-11ea-98b2-99e46f6d77c4.png)

**Comment by clccc** [comment]
Some nodes of inE("REACHING_DEF").outV  does not really define the inV directly.  The 3rd argument "left" does not defined by "pms->buf", "p", "zbx_md5_append(***)", but there are reaching-def edges between them. And the right defined node should be "left-=64" is not the Identifier "left".
On 9/1/2020 08:54，clccc<notifications@github.com> wrote：

I test the newest joern v1.0.186. I found that some reaching-def edges did not labeld VARIABLE. A reaching-def edge should have an associate def-variable, is it right?

**Comment by fabsx00** [comment]
Some of the labels are missing, I'll add those some time this week. When it comes to additional edges: the PDG is now highly overtainted on purpose, a step which I'll need to explain in an article soon. I think it's a good idea though to provide a nice little PDG extraction API that covers this up. This is coming in this week. That should also solve for https://github.com/ShiftLeftSecurity/joern/issues/342

**Comment by clccc** [comment]
Great, I am looking forward to your article.

**Comment by fabsx00** [comment]
@clccc the missing edge labels on data flow edges should be fixed once https://github.com/ShiftLeftSecurity/joern/pull/346/ is merged.

**Comment by fabsx00** [comment]
https://github.com/ShiftLeftSecurity/codepropertygraph/pull/963

**Comment by fabsx00** [comment]
See https://github.com/ShiftLeftSecurity/codepropertygraph/issues/955 - this is fixed now, but you'll need to use `dotDdg` instead of reading the raw edges. I also created `run.dumpDdg` for dumping of the DDG to disk: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/973

**Comment by clccc** [comment]
I test the fixed joern，the result showed below.
![image](https://user-images.githubusercontent.com/12693134/95540451-60da8980-0a23-11eb-9cab-d7304a7991de.png)
I don't know why some reaching-def edges have a " " as VARIABLE. I find this problem persistent alwarys. Is it on purpose? Sorry, I can't understand its reasonableness.
